Add translation to spanish in whats next section
gelopfalcon/101-tutorial pull request #1
Opened 2019-10-18 17:32 UTC by gelopfalcon

2019-10-21 02:20 UTC, ejbogantes requested changes
Solo un comentario para revisar.

2019-10-21 02:20 UTC, ejbogantes commented on docs_es/tutorial/what-next/index.md
> +un contenedor para salir) y luego trabajan para hacer que **estado real** refleje el estado esperado.
No estoy seguro de esa traducción.  Tal vez algo como ¨un contenedor desocupando¨ o ¨un contenedor cerrando¨

2019-10-21 14:09 UTC, gelopfalcon commented on docs_es/tutorial/what-next/index.md
> +un contenedor para salir) y luego trabajan para hacer que **estado real** refleje el estado esperado.
cual traducción?

2019-10-22 01:08 UTC, ejbogantes commented on docs_es/tutorial/what-next/index.md
> +un contenedor para salir) y luego trabajan para hacer que **estado real** refleje el estado esperado.
(como un contenedor para salir)

2019-10-22 14:33 UTC, gelopfalcon commented on docs_es/tutorial/what-next/index.md
> +un contenedor para salir) y luego trabajan para hacer que **estado real** refleje el estado esperado.
done

2019-10-22 14:36 UTC, gelopfalcon reviewed
Applied

2019-10-23 21:51 UTC, ejbogantes approved these changes

2019-10-23 21:53 UTC, merged