Translates /tutorial/index.md
gelopfalcon/101-tutorial pull request #2
Opened 2019-10-21 02:21 UTC by ejbogantes

2019-10-21 14:08 UTC, gelopfalcon commented on docker-compose.yml
> +      context: ./
Porque este cambio?

2019-10-21 14:10 UTC, gelopfalcon commented on docs_es/tutorial/index.md
> +    Puedes combinar parametros de un solo caracter para reducir el tamaño del comando.
parámetros no parametros.

2019-10-21 14:12 UTC, gelopfalcon requested changes
Pequeñas correcciones

2019-10-22 01:09 UTC, ejbogantes commented on docker-compose.yml
> +      context: ./
Era para correr el proyecto, pero ahi vi que alguien más actualizó el proceso.

2019-10-23 21:46 UTC, gelopfalcon approved these changes

2019-10-24 13:48 UTC, merged